blank_issues_enabled: false
contact_links:
  - name: ❓ Discuss something on Discord
    url: https://discord.gg/vBFd8p6H7u
    about: For more interactive discussions, you can join the Polaris Discord server.